exp_name: cacom_corridor
run_name: corridor_s0

env_args:
  map_name: corridor
  seed: 0

seed: 0

encode_dim: 8
request_dim: 10
response_dim: 20
obs_segs: 
  - - 1
    - 4
  - - 12
    - 10
  - - 5
    - 6
  - - 1
    - 2
  - - 1
    - 30
  - - 1
    - 6

start_train_gate: 1_000_000
